name: github_last_10_commits
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.12.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - Icons/

